import mysql.connector
import os
import re
import json
from datetime import datetime, timedelta
from typing import List, Dict, Union, Tuple
from DatabaseManager import DatabaseManager
# ===========================
# User Interface Module
# ===========================
class UserInterface:
    @staticmethod
    def display_results(result: Dict):
        print(f"\n{'=' * 80}")
        print(f"📋 QUERY: {result['query']}")

        # Display SQL if available
        if result.get("sql"):
            print(f"⚙️  GENERATED SQL: {result['sql']}")

        # Handle error cases
        if result["status"] == "error":
            error_msg = result.get('error') or result.get('message') or 'Unknown error'
            print(f"\n❌ ERROR: {error_msg}")
            print(f"{'=' * 80}")
            return

        # Display summary
        if "summary" in result:
            print(f"\n💡 SUMMARY: {result['summary']}")

        # Handle different data formats
        if "data" in result:
            data = result["data"]

            if isinstance(data, (list, tuple)):
                # List data (multiple rows)
                if data:
                    print(f"\n🔢 RAW DATA ({len(data)} rows):")
                    for i, row in enumerate(data[:5], 1):
                        print(f"{i}. {row}")
                    if len(data) > 5:
                        print(f"... showing 5 of {len(data)} rows")
                else:
                    print("\n🔢 RAW DATA: Empty result set")

            elif isinstance(data, dict):
                # Dictionary data (single row)
                print("\n🔢 RAW DATA (dictionary result):")
                for key, value in data.items():
                    print(f"{key}: {value}")

            else:
                # Scalar values (int, float, str, bool)
                print(f"\n🔢 RAW DATA: {data}")

        print(f"{'=' * 80}")
    # (keep get_user_queries method unchanged)

    # @staticmethod
    # # def get_user_queries() -> List[str]:
    # #     """Get queries from user or use sample set"""
    # #     print("\nChoose an option:")
    # #     print("1. Enter custom queries")
    # #     print("2. Run example queries")
    # #     choice = input("Your choice (1/2): ").strip()
    # #
    # #     if choice == "1":
    # #         print("\nEnter queries (one per line, type 'done' to finish):")
    # #         queries = []
    # #         while True:
    # #             query = input("> ").strip()
    # #             if query.lower() == 'done':
    # #                 break
    # #             if query:
    # #                 queries.append(query)
    # #         return queries
    @staticmethod
    def get_user_queries() -> List[str]:
        print("\nEnter queries (one per line, type 'done' to finish):")
        queries = []
        while True:
            query = input("> ").strip()
            # Clean input: remove numbering and quotes
            query = re.sub(r"^\d+\.\s*", "", query)
            query = query.replace("'", "").replace('"', '')

            if query.lower() == 'done':
                break
            if query:
                queries.append(query)
        return queries

        # Predefined example queries
        return [
            "What is the email address of the employee who is the Sales Manager?",
            "Which employees worked more than 40 hours during week 1?",
            "What was the total sales revenue generated by the company during week 1?",
            "Who achieved the highest sales revenue in a single week, and when?",
            "List activities of employees in the Sales department during week 3",
            "Who are the employees that faced challenges with customer retention?",
            "Which employees were hired during a time of industry recession?",
            "Compare the hours worked by 'Wei Zhang' and 'Tao Huang' during week 1",
            "Who are the top 3 employees by total hours worked during the last 4 weeks?",
            "How many employees does the company have in total?"
        ]